name: Deploy to Infomaniak

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 3. Installer les dépendances
      - name: Install dependencies
        working-directory: ./portfolio-Samuel-k
        run: npm install

      # 4. Build du projet Vue/Vite
      - name: Build project
        working-directory: ./portfolio-Samuel-k
        run: npm run build

      # 5. Deploy via SFTP (Infomaniak)
      - name: Deploy via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "portfolio-Samuel-k/dist/*"
          target: "/web/"