name: Deploy to Infomaniak

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 3. Installer les dépendances
      - name: Install dependencies
        working-directory: "./Portfolio Samuel-K"
        run: npm install

      # 4. Build du projet Vue/Vite
      - name: Build project
        working-directory: "./Portfolio Samuel-K"
        run: npm run build

      # 5. Deploy via FTP (Infomaniak)
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: "./Portfolio Samuel-K/dist/"
          server-dir: "/"